
name: testthat-module

on:
  push:
    branches:
      - main
      - development
      - GHA-reuse
  pull_request:
    branches:
      - main
      - development
      - GHA-reuse

jobs:
  testthat-module:
    if: "github.ref == 'refs/heads/main' || !contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          #- {os: ubuntu-latest,  r: 'release'}
          #- {os: macOS-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_AUTH: ${{ secrets.GOOGLE_AUTH }}
      BRANCH_NAME: ${{ github.base_ref || github.ref_name }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:

      - name: Check for Google Authorization
        if: ${{ env.GOOGLE_AUTH == '' }}
        run: exit 1

      - uses: actions/checkout@v4

      - uses: suz-estella/CBM_defaults/.github/actions/setup-SpaDES-tests@GHA-reuse
        with:
           r-version: ${{ matrix.config.r }}

      - name: Run tests
        run: |
          Require::Require("googledrive")
          googledrive::drive_auth(path = Sys.getenv("GOOGLE_AUTH"))

          stop("tests about to run")

          #testthat::test_dir("tests/testthat", filter = "integration", invert = TRUE, stop_on_failure = TRUE)

        shell: Rscript {0}

